name: main pipeline

on:
    push:
        branches:
            - main

jobs:
    build-test:
        uses: ./.github/workflows/reusable-build-test.yml
        with:
            python_version: "3.14"
            run_tests: true

    docker:
        needs: build-test
        uses: ./.github/workflows/reusable-docker.yml
        secrets:
            docker_username: ${{ secrets.DOCKER_USERNAME }}
            docker_token: ${{ secrets.DOCKER_TOKEN }}

    deploy:
        needs: docker
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: install docker and setup folders
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ubuntu
                  key: ${{ secrets.EC2_SSH_KEY }}
                  script: |
                      echo "Installing required packages & folders"
                      sudo apt-get update && sudo apt-get install docker.io docker-compose-v2 -y
                      sudo usermod -aG docker $USER
                      mkdir -p devops

            - name: copy docker-compose file to ec2
              uses: appleboy/scp-action@v1
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ubuntu
                  key: ${{ secrets.EC2_SSH_KEY }}
                  source: docker-compose.yml
                  target: ~/devops

            - name: deploy the app
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ubuntu
                  key: ${{ secrets.EC2_SSH_KEY }}
                  script: |
                      cd ~/devops
                      sudo docker compose pull
                      sudo docker compose down || true
                      sudo docker compose up -d
                      echo " Deployed successfully!"
